/*
SendPost API

Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.

API version: 1.0.0
Contact: hello@sendpost.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sendpost

import (
	"encoding/json"
)

// checks if the To type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &To{}

// To struct for To
type To struct {
	Name *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
	Cc []CopyTo `json:"cc,omitempty"`
	Bcc []CopyTo `json:"bcc,omitempty"`
	CustomFields map[string]interface{} `json:"customFields,omitempty"`
}

// NewTo instantiates a new To object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTo() *To {
	this := To{}
	return &this
}

// NewToWithDefaults instantiates a new To object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewToWithDefaults() *To {
	this := To{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *To) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *To) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *To) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *To) SetName(v string) {
	o.Name = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *To) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *To) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *To) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *To) SetEmail(v string) {
	o.Email = &v
}

// GetCc returns the Cc field value if set, zero value otherwise.
func (o *To) GetCc() []CopyTo {
	if o == nil || IsNil(o.Cc) {
		var ret []CopyTo
		return ret
	}
	return o.Cc
}

// GetCcOk returns a tuple with the Cc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *To) GetCcOk() ([]CopyTo, bool) {
	if o == nil || IsNil(o.Cc) {
		return nil, false
	}
	return o.Cc, true
}

// HasCc returns a boolean if a field has been set.
func (o *To) HasCc() bool {
	if o != nil && !IsNil(o.Cc) {
		return true
	}

	return false
}

// SetCc gets a reference to the given []CopyTo and assigns it to the Cc field.
func (o *To) SetCc(v []CopyTo) {
	o.Cc = v
}

// GetBcc returns the Bcc field value if set, zero value otherwise.
func (o *To) GetBcc() []CopyTo {
	if o == nil || IsNil(o.Bcc) {
		var ret []CopyTo
		return ret
	}
	return o.Bcc
}

// GetBccOk returns a tuple with the Bcc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *To) GetBccOk() ([]CopyTo, bool) {
	if o == nil || IsNil(o.Bcc) {
		return nil, false
	}
	return o.Bcc, true
}

// HasBcc returns a boolean if a field has been set.
func (o *To) HasBcc() bool {
	if o != nil && !IsNil(o.Bcc) {
		return true
	}

	return false
}

// SetBcc gets a reference to the given []CopyTo and assigns it to the Bcc field.
func (o *To) SetBcc(v []CopyTo) {
	o.Bcc = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *To) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *To) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *To) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *To) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

func (o To) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o To) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Cc) {
		toSerialize["cc"] = o.Cc
	}
	if !IsNil(o.Bcc) {
		toSerialize["bcc"] = o.Bcc
	}
	if !IsNil(o.CustomFields) {
		toSerialize["customFields"] = o.CustomFields
	}
	return toSerialize, nil
}

type NullableTo struct {
	value *To
	isSet bool
}

func (v NullableTo) Get() *To {
	return v.value
}

func (v *NullableTo) Set(val *To) {
	v.value = val
	v.isSet = true
}

func (v NullableTo) IsSet() bool {
	return v.isSet
}

func (v *NullableTo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTo(val *To) *NullableTo {
	return &NullableTo{value: val, isSet: true}
}

func (v NullableTo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


