/*
SendPost API

Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.

API version: 1.0.0
Contact: hello@sendpost.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sendpost

import (
	"encoding/json"
)

// checks if the Os type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Os{}

// Os struct for Os
type Os struct {
	Family *string `json:"Family,omitempty"`
	Major *string `json:"Major,omitempty"`
	Minor *string `json:"Minor,omitempty"`
	Patch *string `json:"Patch,omitempty"`
	PatchMinor *string `json:"PatchMinor,omitempty"`
}

// NewOs instantiates a new Os object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOs() *Os {
	this := Os{}
	return &this
}

// NewOsWithDefaults instantiates a new Os object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOsWithDefaults() *Os {
	this := Os{}
	return &this
}

// GetFamily returns the Family field value if set, zero value otherwise.
func (o *Os) GetFamily() string {
	if o == nil || IsNil(o.Family) {
		var ret string
		return ret
	}
	return *o.Family
}

// GetFamilyOk returns a tuple with the Family field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Os) GetFamilyOk() (*string, bool) {
	if o == nil || IsNil(o.Family) {
		return nil, false
	}
	return o.Family, true
}

// HasFamily returns a boolean if a field has been set.
func (o *Os) HasFamily() bool {
	if o != nil && !IsNil(o.Family) {
		return true
	}

	return false
}

// SetFamily gets a reference to the given string and assigns it to the Family field.
func (o *Os) SetFamily(v string) {
	o.Family = &v
}

// GetMajor returns the Major field value if set, zero value otherwise.
func (o *Os) GetMajor() string {
	if o == nil || IsNil(o.Major) {
		var ret string
		return ret
	}
	return *o.Major
}

// GetMajorOk returns a tuple with the Major field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Os) GetMajorOk() (*string, bool) {
	if o == nil || IsNil(o.Major) {
		return nil, false
	}
	return o.Major, true
}

// HasMajor returns a boolean if a field has been set.
func (o *Os) HasMajor() bool {
	if o != nil && !IsNil(o.Major) {
		return true
	}

	return false
}

// SetMajor gets a reference to the given string and assigns it to the Major field.
func (o *Os) SetMajor(v string) {
	o.Major = &v
}

// GetMinor returns the Minor field value if set, zero value otherwise.
func (o *Os) GetMinor() string {
	if o == nil || IsNil(o.Minor) {
		var ret string
		return ret
	}
	return *o.Minor
}

// GetMinorOk returns a tuple with the Minor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Os) GetMinorOk() (*string, bool) {
	if o == nil || IsNil(o.Minor) {
		return nil, false
	}
	return o.Minor, true
}

// HasMinor returns a boolean if a field has been set.
func (o *Os) HasMinor() bool {
	if o != nil && !IsNil(o.Minor) {
		return true
	}

	return false
}

// SetMinor gets a reference to the given string and assigns it to the Minor field.
func (o *Os) SetMinor(v string) {
	o.Minor = &v
}

// GetPatch returns the Patch field value if set, zero value otherwise.
func (o *Os) GetPatch() string {
	if o == nil || IsNil(o.Patch) {
		var ret string
		return ret
	}
	return *o.Patch
}

// GetPatchOk returns a tuple with the Patch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Os) GetPatchOk() (*string, bool) {
	if o == nil || IsNil(o.Patch) {
		return nil, false
	}
	return o.Patch, true
}

// HasPatch returns a boolean if a field has been set.
func (o *Os) HasPatch() bool {
	if o != nil && !IsNil(o.Patch) {
		return true
	}

	return false
}

// SetPatch gets a reference to the given string and assigns it to the Patch field.
func (o *Os) SetPatch(v string) {
	o.Patch = &v
}

// GetPatchMinor returns the PatchMinor field value if set, zero value otherwise.
func (o *Os) GetPatchMinor() string {
	if o == nil || IsNil(o.PatchMinor) {
		var ret string
		return ret
	}
	return *o.PatchMinor
}

// GetPatchMinorOk returns a tuple with the PatchMinor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Os) GetPatchMinorOk() (*string, bool) {
	if o == nil || IsNil(o.PatchMinor) {
		return nil, false
	}
	return o.PatchMinor, true
}

// HasPatchMinor returns a boolean if a field has been set.
func (o *Os) HasPatchMinor() bool {
	if o != nil && !IsNil(o.PatchMinor) {
		return true
	}

	return false
}

// SetPatchMinor gets a reference to the given string and assigns it to the PatchMinor field.
func (o *Os) SetPatchMinor(v string) {
	o.PatchMinor = &v
}

func (o Os) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Os) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Family) {
		toSerialize["Family"] = o.Family
	}
	if !IsNil(o.Major) {
		toSerialize["Major"] = o.Major
	}
	if !IsNil(o.Minor) {
		toSerialize["Minor"] = o.Minor
	}
	if !IsNil(o.Patch) {
		toSerialize["Patch"] = o.Patch
	}
	if !IsNil(o.PatchMinor) {
		toSerialize["PatchMinor"] = o.PatchMinor
	}
	return toSerialize, nil
}

type NullableOs struct {
	value *Os
	isSet bool
}

func (v NullableOs) Get() *Os {
	return v.value
}

func (v *NullableOs) Set(val *Os) {
	v.value = val
	v.isSet = true
}

func (v NullableOs) IsSet() bool {
	return v.isSet
}

func (v *NullableOs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOs(val *Os) *NullableOs {
	return &NullableOs{value: val, isSet: true}
}

func (v NullableOs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


